spring.application.name=medicaments-api
# Base de datos
spring.datasource.url=jdbc:postgresql://localhost:5433/medicaments
spring.datasource.username=postgres
spring.datasource.password=postgres

# JPA / Hibernate
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true

#JWT expire in 60 minuts
jwt.secret=8F3kL9pQ2xV7mN4zR6tY1wE5aS0dH3jK
jwt.expiration=3600000


logging.level.org.springframework.security=TRACE
logging.level.org.springframework.web=DEBUG